// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeI5w-XR5RWPJsNzmCynYXBggPW3CA-18',
    appId: '1:361776729383:web:eca82b129caafe7a776d02',
    messagingSenderId: '361776729383',
    projectId: 'datakap-374ec',
    authDomain: 'datakap-374ec.firebaseapp.com',
    storageBucket: 'datakap-374ec.firebasestorage.app',
    measurementId: 'G-XV03F009F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDhJ5WM_NKfz5s9DfKvM39mjpS1a87uAs',
    appId: '1:361776729383:android:ec6be5eab15e2727776d02',
    messagingSenderId: '361776729383',
    projectId: 'datakap-374ec',
    storageBucket: 'datakap-374ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt3t_CjHdaQ-Xx8RpCiNHUhIASUNYAR0Q',
    appId: '1:361776729383:ios:912d854b51333bbd776d02',
    messagingSenderId: '361776729383',
    projectId: 'datakap-374ec',
    storageBucket: 'datakap-374ec.firebasestorage.app',
    iosBundleId: 'com.afiliacionesmx.datakap.datakap',
  );
}
